#!/bin/bash

SCRIPT_PATH="${BASH_SOURCE[0]}";
if ([ -h "${SCRIPT_PATH}" ]) then
  while([ -h "${SCRIPT_PATH}" ]) do SCRIPT_PATH=`readlink "${SCRIPT_PATH}"`; done
fi
pushd . > /dev/null
cd `dirname ${SCRIPT_PATH}` > /dev/null
SCRIPT_PATH=`pwd`;
popd  > /dev/null

SQUID_SHARED="${SCRIPT_PATH}/shared"

if ! $(docker ps -a | grep -q squid3); then
  echo 'Creating squid container'
  docker run -ti -P -d \
        -h squid3.dev\
        -v $SQUID_SHARED/cache:/var/cache/squid3 \
        -v $SQUID_SHARED/certs:/etc/squid3/certs \
        --name squid3 \
        fgrehm/squid3-ssl:v20140809
else
  if ! $(docker ps | grep -q squid3); then
    echo 'Restarting squid container'
    sudo mkdir -p $SQUID_SHARED/{certs,cache}
    docker start squid3 &> /dev/null
  else
    echo 'Squid container is already running'
  fi
fi
